networks:
  loki:

services:
  carnivorous-garden:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/carnivorous-garden/logs/
    networks:
      - loki
    ports:
      - 5000:5000

  alloy:
    image: grafana/alloy:v1.2.1
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./logs:/logs/
    networks:
      - loki
    ports:
      - 12345:12345
    depends_on:
      - carnivorous-garden
      - loki
    command: run --disable-reporting --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

  loki:
    image: grafana/loki:3.1.0
    volumes:
      - ./loki-config.yml:/etc/loki/config.yaml
    networks:
      - loki
    depends_on:
      - minio
      - createbuckets
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/config.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    volumes:
      - ~/minio/data:/data
    networks:
      - loki
    ports:
      - 9000:9000
      - 9001:9001
    command: server ~ --address ":9000" --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 15s
      timeout: 10s
      retries: 5

  createbuckets:
    image: minio/mc
    networks:
      - loki
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/loki;
      /usr/bin/mc anonymous set public myminio/loki;
      exit 0;
      "

  grafana:
    image: grafana/grafana:10.4.5
    volumes:
      - ./grafana/provisioning:/var/lib/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
    networks:
      - loki
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
