auth_enabled: false


server:  # Is this needed?
  http_listen_port: 3100


limits_config:  # Is this needed?
  allow_structured_metadata: true
  volume_enabled: true


common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  storage:
    s3:
      endpoint: minio.:9000
      insecure: true
      bucketnames: loki
      access_key_id: minioadmin
      secret_access_key: minioadmin
      s3forcepathstyle: true


storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    resync_interval: 5s
  aws:
    s3: s3://minioadmin:minioadmin@minio.:9000/loki
    s3forcepathstyle: true


schema_config:
  configs:
  - from: 2022-01-11
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h


pattern_ingester:  # Is this needed?
  enabled: true
