auth_enabled: false


limits_config:
  allow_structured_metadata: true
  volume_enabled: true


server:
  http_listen_port: 3100


common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: chunks
      access_key_id: herpyderpy
      secret_access_key: herpyderpy
      s3forcepathstyle: true


storage_config:
  aws:
    s3: s3://herpyderpy:herpyderpy@minio:9001
    s3forcepathstyle: true
    bucketnames: chunks
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache


schema_config:
  configs:
  - from: 2020-07-01
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h


pattern_ingester:
  enabled: true
